#!/bin/bash
#
# This script creates a virtualenv named 'env', installs the Python
# requirements, and then runs the development server.  If 'env' already
# exists, it is activated and used as-is.
#
# From: electrum/electrum-env
# Modified: procrasti@k5-stats.org 13 Aug 2015

PYTHON=python3

export DJANGO_SETTINGS_MODULE="k666.settings"
export DEFAULT_DATABASE="sqlite3"
export DEBUG=True

if which ${PYTHON}; then
    if ! [ -e ./env/bin/activate ]; then
        if which virtualenv; then
            virtualenv env -p ${PYTHON}
        else
            echo "virtualenv not found, using built in venv"
            ${PYTHON} -m venv env
        fi
    fi

    source ./env/bin/activate
    # Install project dependencies
    pip install -r requirements.txt
    python setup.py install

        # WHY DOESN'T THIS WORK FROM setup.py?
        # pip install django-recaptcha2

        # if ! [ -e k666 ]; then
        #     django-admin startproject k666 .
        # fi

        # DONT LET THIS INTO PRODUCTION!!!
        # ASSUMING DEV ENVIRONMENT... ITS VERY WRONG
        # IS OKAY IF USING SQLITE3... BUT WE DON'T KNOW!
        if ! [ -e db.sqlite3 ]; then
            ## 1. Create the database tables/migrations
            ./manage.py migrate

            ## 2. Create the Super User or Admin account with a user name and password.
            ./manage.py createsuperuser
        fi


    ./manage.py runserver "$@"
    # deactivate
else
    echo "You probably have to install ${PYTHON}"
    echo "sudo apt-get install python3?"
fi

